/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlConsulta;
import Control.Globales;
import static Vista.VistaPrincipal.escritorio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SeeD
 */
public class aleatorioEstratificado extends javax.swing.JPanel {

    /**
     * Creates new form aleatorioEstratificado
     */
    public aleatorioEstratificado(ControlConsulta control) {
        initComponents();
        this.jtTablesEstratificado.setTitleAt(0, "Tab/Condiciones");
        this.jtTablesEstratificado.setTitleAt(1, "Estratos");
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtNoEstratos = new javax.swing.JTextField();
        jbGenerateStratos = new javax.swing.JButton();
        jtTablesEstratificado = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCaracteristicas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtEstratosGenerados = new javax.swing.JTable();
        jbGenerarMuestra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Nº Estratos");

        jtNoEstratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNoEstratosActionPerformed(evt);
            }
        });

        jbGenerateStratos.setText("generarEstratos");
        jbGenerateStratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerateStratosActionPerformed(evt);
            }
        });

        jtCaracteristicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caracteristica/Estrato"
            }
        ));
        jScrollPane3.setViewportView(jtCaracteristicas);
        if (jtCaracteristicas.getColumnModel().getColumnCount() > 0) {
            jtCaracteristicas.getColumnModel().getColumn(0).setResizable(false);
        }

        jtTablesEstratificado.addTab("tab1", jScrollPane3);

        jtEstratosGenerados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtEstratosGenerados);

        jtTablesEstratificado.addTab("tab2", jScrollPane4);

        jbGenerarMuestra.setText("Generar Muestra");
        jbGenerarMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarMuestraActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite El numero de estratos a generar con sus respectivas condiciones");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Ejemplo para la caracteristca : numUno- numDos  ò  num   ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Muestreo Aleatorio Estratificado :");

        jLabel5.setText("Luego presione en \"generarEstratos\" & luego en \"Generar Muestra\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtTablesEstratificado, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNoEstratos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jbGenerateStratos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGenerarMuestra))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNoEstratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGenerateStratos)
                    .addComponent(jbGenerarMuestra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTablesEstratificado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalir)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtNoEstratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNoEstratosActionPerformed
        // TODO add your handling code here:
        if (this.jtNoEstratos.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite un Nuemero de Estratos!!");
        } else {
            if (Globales.verificarSiEsNum(this.jtNoEstratos.getText()) && Integer.parseInt(this.jtNoEstratos.getText()) > 0) {
                this.nEstratos = Integer.parseInt(this.jtNoEstratos.getText());
                DefaultTableModel def = (DefaultTableModel) this.jtCaracteristicas.getModel();
                def.setRowCount(0);
                for (int i = 0; i < this.nEstratos; i++) {
                    def.addRow(new Object[1]);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Digite Un Numero Entero Naural Por Favor!!");
            }
        }
    }//GEN-LAST:event_jtNoEstratosActionPerformed

    private void jbGenerateStratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerateStratosActionPerformed
        // TODO add your handling code here:
        if (control.validarCondicionEstratos(jtCaracteristicas)) {
            control.generarEstratos(jtCaracteristicas, jtEstratosGenerados);
            jtTablesEstratificado.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "Las Condiciones no estan Bien escritas !!!");
        }

    }//GEN-LAST:event_jbGenerateStratosActionPerformed

    private void jbGenerarMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarMuestraActionPerformed
        // TODO add your handling code here:
        if (jtEstratosGenerados.getColumnCount() > 0) {
            control.calcularPoblacionTotalStratos(jtEstratosGenerados, nEstratos);
        } else {
            JOptionPane.showMessageDialog(this, "No se Han Generado Los Estratos");
        }
    }//GEN-LAST:event_jbGenerarMuestraActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbGenerarMuestra;
    private javax.swing.JButton jbGenerateStratos;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable jtCaracteristicas;
    private javax.swing.JTable jtEstratosGenerados;
    private javax.swing.JTextField jtNoEstratos;
    private javax.swing.JTabbedPane jtTablesEstratificado;
    // End of variables declaration//GEN-END:variables
    private int nEstratos = 0;
    private ControlConsulta control;
}
