/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlConsulta;
import Control.Globales;
import static Vista.VistaPrincipal.escritorio;
import static Vista.VistaPrincipal.jtMuestra;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SeeD
 */
public class aleatorioConglomerados extends javax.swing.JPanel {

    /**
     * Creates new form aleatorioConglomerados
     */
    public aleatorioConglomerados(ControlConsulta control) {
        initComponents();
        this.control = control;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtNumConglomerados = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlCaracteristicas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGrupos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtIntervalos = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Nº Conglomerado Para la Poblacion : ");

        jtNumConglomerados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumConglomeradosActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoja Cada Conglomerado.  A continuacion Digite Indices");

        jlCaracteristicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));
        jlCaracteristicas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlCaracteristicas.setDragEnabled(true);
        jlCaracteristicas.setFocusTraversalPolicyProvider(true);
        jScrollPane1.setViewportView(jlCaracteristicas);

        jtGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtGrupos);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText(" De 1 hasta N separados por un guion(-) para escoger los Grupos de Su poblacion. Luego presiones \"Generar Muestra\"");

        jtIntervalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIntervalosActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Muestra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Muestreo Aleatorio Por Conglomerados : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Rango Del Grupo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(jButton2)))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtNumConglomerados, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNumConglomerados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jtIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtNumConglomeradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumConglomeradosActionPerformed
        // TODO add your handling code here:+
        if (Globales.verificarSiEsNum(jtNumConglomerados.getText())) {
            numConglomerados = Integer.parseInt(jtNumConglomerados.getText());
            if (numConglomerados < 0) {
                JOptionPane.showMessageDialog(this, "El numero de Conglomerados no puede ser negativo");
            } else {
                if (numConglomerados > control.getConsulta().getn()) {
                    JOptionPane.showMessageDialog(this, "El numero de Conglomerados no puede ser mayor que el de la Muestra");
                } else {
                    DefaultTableModel def = (DefaultTableModel) jtGrupos.getModel();
                    if (def.getRowCount() > 0) {
                        ((DefaultListModel) jlCaracteristicas.getModel()).removeAllElements();
                    }
                    def.setColumnCount(0);
                    for (int i = 0; i < numConglomerados; i++) {
                        def.addColumn("Grup. " + (i + 1));
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No has digitado un Numero de Conglomerados");
        }

    }//GEN-LAST:event_jtNumConglomeradosActionPerformed

    private void jtIntervalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIntervalosActionPerformed
        // TODO add your handling code here:

        if (jlCaracteristicas.getModel().getSize() < numConglomerados) {
            if (Globales.verificarConglomerado(jtIntervalos.getText())) {
                int[] inter = new int[2];
                inter[0] = Integer.parseInt(jtIntervalos.getText().split("-")[0]);
                inter[1] = Integer.parseInt(jtIntervalos.getText().split("-")[1]);
                if (inter[0] > control.getConsulta().getN() || inter[1] > control.getConsulta().getN() || inter[0] < 0 || inter[1] < 0) {
                    JOptionPane.showMessageDialog(this, "En este intervalo hay elementos fuera de la poblacion");
                } else {
                    modelListaCong.addElement("[" + jtIntervalos.getText() + "]");
                    jlCaracteristicas.setModel(modelListaCong);
                    jtGrupos.setModel(control.agregarConglomerado(jtGrupos, inter, jlCaracteristicas.getModel().getSize() - 1));
                }
            } else {
                JOptionPane.showMessageDialog(this, "El Intervalo Fue Mal Escrito. Digite numeros positivos dentro del intervalo [1-N]");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El Numero de Conglomerados ya Fue Escogito");
        }
    }//GEN-LAST:event_jtIntervalosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jlCaracteristicas.getModel().getSize() == numConglomerados) {
            control.aleatorioConglomerados(jtGrupos);
            jtMuestra.setModel(Globales.cargarDatosJtable(control.getConsulta().getnDatos(), control.getConsulta().getElementos()));
            jtMuestra.getColumnModel().getColumn(0).setPreferredWidth(30);
        } else {
            JOptionPane.showMessageDialog(this, "NO has terminado de Ingresar tus Grupos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> jlCaracteristicas;
    private javax.swing.JTable jtGrupos;
    private javax.swing.JTextField jtIntervalos;
    private javax.swing.JTextField jtNumConglomerados;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel modelListaCong = new DefaultListModel();
    private int numConglomerados = 0;
    private ControlConsulta control;
}
