/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlConsulta;
import Control.Globales;
import static Vista.VistaPrincipal.escritorio;
import static Vista.VistaPrincipal.jtMuestra;
import static Vista.VistaPrincipal.jtTables;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SeeD
 */
public class muestreoCuotas extends javax.swing.JPanel {

    /**
     * Creates new form muestreoCuotas
     */
    public muestreoCuotas(ControlConsulta control) {
        initComponents();
        this.control = control;
        this.listModelCarac = new DefaultListModel();
        this.listModelMuestra = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlCaracteristicas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jtCaracteristica = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGrupos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlMuestra = new javax.swing.JList<>();
        jbSalir = new javax.swing.JButton();
        jbIncluir = new javax.swing.JButton();
        jbQuitar = new javax.swing.JButton();
        jbGenerar = new javax.swing.JButton();
        jtNºGrupos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        jlCaracteristicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Caracteristica/Grpos"));
        jScrollPane1.setViewportView(jlCaracteristicas);

        jLabel1.setText("2) Digite la caracteristica de cada Subgrupo. Separe con un Guion.  (numUno-numDos) Ò num           ");

        jtCaracteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCaracteristicaActionPerformed(evt);
            }
        });

        jtGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtGrupos.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(jtGrupos);

        jlMuestra.setBorder(javax.swing.BorderFactory.createTitledBorder("MuestraAux"));
        jScrollPane3.setViewportView(jlMuestra);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbIncluir.setText("incluir");
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });

        jbQuitar.setText("Quitar");
        jbQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitarActionPerformed(evt);
            }
        });

        jbGenerar.setText("Generar Muestra");
        jbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarActionPerformed(evt);
            }
        });

        jtNºGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNºGruposActionPerformed(evt);
            }
        });

        jLabel2.setText("NºGrupos");

        jLabel3.setText("Caracteristica");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Muestreo Por Cuotas:");

        jLabel5.setText("1 ) Digite El numero de grupos que desea obtener de la poblacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbGenerar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(16, 16, 16)
                                        .addComponent(jtCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtNºGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbIncluir)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jbSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbQuitar)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNºGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtCaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbGenerar)
                        .addComponent(jbSalir)))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtCaracteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCaracteristicaActionPerformed
        // TODO add your handling code here:
        if (listModelCarac.getSize() < nGrupos) {
            if (jtCaracteristica.getText().indexOf("-") > -1) {
                if (Globales.verificarConglomerado(jtCaracteristica.getText())) {
                    listModelCarac.addElement("[" + jtCaracteristica.getText() + ")");
                    jlCaracteristicas.setModel(listModelCarac);
                    int[] carac = new int[2];
                    String[] caract = jtCaracteristica.getText().split("-");
                    carac[0] = Integer.parseInt(caract[0]);
                    carac[1] = Integer.parseInt(caract[1]);
                    jtGrupos.setModel(control.generarGrupo(jtGrupos, carac, listModelCarac.getSize() - 1));
                    jtCaracteristica.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "La caracteristica no es valida");
                }
            } else {
                if (Globales.verificarSiEsNum(jtCaracteristica.getText())) {
                    int num = Integer.parseInt(jtCaracteristica.getText());
                    listModelCarac.addElement(num);
                    jlCaracteristicas.setModel(listModelCarac);
                    jtGrupos.setModel(control.generarGrupo(jtGrupos, num, listModelCarac.getSize() - 1));
                    jtCaracteristica.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "La Caracteristica Esta Mal Digitada");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ya se Ingresaron Todas las Caracteristicas");
        }
    }//GEN-LAST:event_jtCaracteristicaActionPerformed

    private void jbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarActionPerformed
        // TODO add your handling code here:
        if (listModelMuestra.getSize() > 0) {
            control.jlistAtabla(listModelMuestra);
            jtMuestra.setModel(Globales.cargarDatosJtable(control.getConsulta().getnDatos(), control.getConsulta().getElementos()));
            jtTables.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "No hay elementos para añadir a la muestra");
        }
    }//GEN-LAST:event_jbGenerarActionPerformed

    private void jtNºGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNºGruposActionPerformed
        // TODO add your handling code here:
        if (jtNºGrupos.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No has digitado el numero de Grupos !!!");
        } else {
            if (Globales.verificarSiEsNum(jtNºGrupos.getText())) {
                nGrupos = Integer.parseInt(jtNºGrupos.getText());
                if (nGrupos > control.getConsulta().getn() || nGrupos < 1) {
                    JOptionPane.showMessageDialog(this, "El numero de Conglomerados no puede ser mayor que el de la Muestra o ser Un dato Negativo");
                } else {
                    DefaultTableModel def = (DefaultTableModel) jtGrupos.getModel();
                    def.setColumnCount(0);
                    if (listModelCarac.getSize() > 0) {
                        listModelCarac.setSize(0);
                    }
                    for (int i = 0; i < nGrupos; i++) {
                        def.addColumn("Grup. " + (i + 1));
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, jtNºGrupos.getText() + " No es Un dato Correcto !!!");
            }
        }

    }//GEN-LAST:event_jtNºGruposActionPerformed

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        // TODO add your handling code here:
        int[] rowsSelection = jtGrupos.getSelectedRows();
        int[] columSelection = jtGrupos.getSelectedColumns();
        if (rowsSelection.length > 0 && columSelection.length > 0) {
            control.agregarAlist(listModelMuestra, columSelection, rowsSelection, jtGrupos);
            jlMuestra.setModel(listModelMuestra);
        } else {
            JOptionPane.showMessageDialog(this, "No has seleccionado ningun elemento");
        }
    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitarActionPerformed
        // TODO add your handling code here:
        if (jlMuestra.getSelectedIndex() >= 0) {
            jlMuestra.setModel(control.eliminarJlmuestra(jlMuestra.getSelectedIndices(), listModelMuestra));
        } else {
            JOptionPane.showMessageDialog(this, "No Has Seleccionado Ningun Elemento en la Muestra");
        }
    }//GEN-LAST:event_jbQuitarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbGenerar;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbQuitar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JList<String> jlCaracteristicas;
    private javax.swing.JList<String> jlMuestra;
    private javax.swing.JTextField jtCaracteristica;
    private javax.swing.JTable jtGrupos;
    private javax.swing.JTextField jtNºGrupos;
    // End of variables declaration//GEN-END:variables
    private ControlConsulta control;
    private DefaultListModel listModelCarac;
    private int nGrupos;
    private DefaultListModel listModelMuestra;
}
