/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlConsulta;
import Control.Globales;
import static Vista.VistaPrincipal.escritorio;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.math3.distribution.NormalDistribution;

/**
 *
 * @author SeeD
 */
public class panelIntervalos extends javax.swing.JPanel {

    /**
     * Creates new form panelIntervalos
     */
    public panelIntervalos(ControlConsulta control) {
        initComponents();
        this.control = control;
        jtTablaIntervalos.setTitleAt(0, "Media Poblacional [µ]");
        jtTablaIntervalos.setTitleAt(1, "Proporciones [P]");
        jtTablaIntervalos.setTitleAt(2, "Varianza [σ^2]");
        jtTablaIntervalos.setTitleAt(3, "Diferencia De Medias [µ1-µ2]");
    }
    boolean verificacion1 = false;
    boolean verificacion2 = false;
    boolean verificacion3 = false;
    boolean verificacion4 = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtTablaIntervalos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlIcX = new javax.swing.JLabel();
        jtX = new javax.swing.JTextField();
        jtNc = new javax.swing.JTextField();
        jtSigma = new javax.swing.JTextField();
        jtS = new javax.swing.JTextField();
        jtn = new javax.swing.JTextField();
        jbOk = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jrnMenor = new javax.swing.JRadioButton();
        jrnMayor = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtp = new javax.swing.JTextField();
        jtNcDos = new javax.swing.JTextField();
        jynDos = new javax.swing.JTextField();
        jlIcP = new javax.swing.JLabel();
        jbOkDos = new javax.swing.JButton();
        jbSalirDos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtVar = new javax.swing.JTextField();
        jtnUno = new javax.swing.JTextField();
        jtNcUno = new javax.swing.JTextField();
        jlIcVar = new javax.swing.JLabel();
        jbOkUno = new javax.swing.JButton();
        jbSalirUno = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtxUno = new javax.swing.JTextField();
        jtxDos = new javax.swing.JTextField();
        jtVarDos = new javax.swing.JTextField();
        jtsUno = new javax.swing.JTextField();
        jtNcTres = new javax.swing.JTextField();
        jrMenorUno = new javax.swing.JRadioButton();
        jrMayorUno = new javax.swing.JRadioButton();
        jlIcMiu = new javax.swing.JLabel();
        jbOkTres = new javax.swing.JButton();
        jbSalirTres = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jtnTresDos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtnTresUno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtSdos = new javax.swing.JTextField();
        jtVarUno = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        check3 = new javax.swing.JCheckBox();
        jTextField28 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        check4 = new javax.swing.JCheckBox();
        jTextField45 = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        botonCalcular8 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel79 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel77 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));

        jtTablaIntervalos.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("X");

        jLabel3.setText("NC(%)");

        jLabel4.setText("σ");

        jLabel5.setText("s");

        jLabel6.setText("n");

        jlIcX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlIcX.setText("Intervalo Confianza (X) =  ");

        jtX.setEditable(false);

        jtNc.setEditable(false);

        jtSigma.setEditable(false);
        jtSigma.setDisabledTextColor(new java.awt.Color(51, 204, 255));
        jtSigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSigmaActionPerformed(evt);
            }
        });

        jtS.setEditable(false);

        jtn.setEditable(false);

        jbOk.setText("ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jrnMenor.setBackground(new java.awt.Color(255, 255, 255));
        jrnMenor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrnMenor.setText("n < 30 && \"S\" Conocida");
        jrnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrnMenorActionPerformed(evt);
            }
        });

        jrnMayor.setBackground(new java.awt.Color(255, 255, 255));
        jrnMayor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrnMayor.setText("n > 30 && \"σ\" Conocida");
        jrnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrnMayorActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Halle un Intervalo de Confianza para el estimador X");

        jLabel21.setText("Segun el tamaño de la muestra ( \"n\" )  y \"σ\" o \"s\"");

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));

        jSeparator9.setForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jSeparator1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jlIcX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalir)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtS)
                                            .addComponent(jtX))
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbOk))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtNc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrnMenor)
                                    .addComponent(jrnMayor))))
                        .addContainerGap(133, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jrnMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jrnMayor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jbOk))
                .addGap(37, 37, 37)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jlIcX))
                .addContainerGap())
        );

        jtTablaIntervalos.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("p(%)");

        jLabel9.setText("NC(%)");

        jLabel10.setText("n");

        jlIcP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlIcP.setText("Intervalo De Confianza(p) =");

        jbOkDos.setText("Ok");
        jbOkDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkDosActionPerformed(evt);
            }
        });

        jbSalirDos.setText("Salir");
        jbSalirDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirDosActionPerformed(evt);
            }
        });

        jLabel23.setText("Los datos en forma de porcentaje se deben digitan de 0 % al 100 % ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Intevalo De Confianza Para P Gorro:");

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));

        jLabel25.setText(" ò  de forma deciamal de 0 a 1");

        jSeparator10.setForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNcDos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jynDos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addComponent(jbOkDos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlIcP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSalirDos)))
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNcDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jynDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jbOkDos))
                .addGap(39, 39, 39)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalirDos)
                    .addComponent(jlIcP))
                .addGap(15, 15, 15))
        );

        jtTablaIntervalos.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("S^2");

        jLabel13.setText("n");

        jLabel14.setText("NC(%)");

        jlIcVar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlIcVar.setText("Intervalo Confianza(σ^2) = ");

        jbOkUno.setText("ok");
        jbOkUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkUnoActionPerformed(evt);
            }
        });

        jbSalirUno.setText("Salir");
        jbSalirUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirUnoActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Intervalo de Confianza Para la Varianza Poblacional:");

        jLabel27.setText("Dijite valores positivos y una muestra menor o igual a 30  ");

        jSeparator4.setForeground(new java.awt.Color(51, 102, 255));

        jSeparator8.setForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(570, Short.MAX_VALUE)
                        .addComponent(jbSalirUno))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtnUno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jtNcUno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtVar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jbOkUno))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator4)
                                .addComponent(jlIcVar, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtnUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOkUno)
                    .addComponent(jtNcUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(44, 44, 44)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalirUno)
                    .addComponent(jlIcVar))
                .addContainerGap())
        );

        jtTablaIntervalos.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("X1");

        jLabel17.setText("X2");

        jLabel18.setText("σ^2");

        jLabel19.setText("S^2");

        jLabel20.setText("NC(%)");

        jtxUno.setEditable(false);

        jtxDos.setEditable(false);

        jtVarDos.setEditable(false);

        jtsUno.setEditable(false);

        jtNcTres.setEditable(false);

        jrMenorUno.setBackground(new java.awt.Color(255, 255, 255));
        jrMenorUno.setText("n<30 & Var desconocida");
        jrMenorUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMenorUnoActionPerformed(evt);
            }
        });

        jrMayorUno.setBackground(new java.awt.Color(255, 255, 255));
        jrMayorUno.setText("n> 30 & var Conocida");
        jrMayorUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMayorUnoActionPerformed(evt);
            }
        });

        jlIcMiu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlIcMiu.setText("Intervalo Confianza (µ1 - µ2) = ");

        jbOkTres.setText("ok");
        jbOkTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkTresActionPerformed(evt);
            }
        });

        jbSalirTres.setText("Salir");
        jbSalirTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirTresActionPerformed(evt);
            }
        });

        jLabel22.setText("n2");

        jtnTresDos.setEditable(false);

        jLabel7.setText("n1");

        jtnTresUno.setEditable(false);

        jLabel11.setText("S^2");

        jtSdos.setEditable(false);

        jtVarUno.setEditable(false);

        jLabel28.setText("σ^2");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Intervalo de Confianza para la diferencia de medias:");

        jLabel30.setText("Ingresa los datos dependiendo del tamaño de la muestra (n) y σ^2 o s");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Muestra Uno : ");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Muestra Dos :");

        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));

        jSeparator7.setForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel7))
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxUno, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jtVarUno)
                                            .addComponent(jtsUno)
                                            .addComponent(jtnTresUno))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtSdos)
                                            .addComponent(jtVarDos)
                                            .addComponent(jtnTresDos)
                                            .addComponent(jtxDos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtNcTres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbOkTres))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrMenorUno)
                                    .addComponent(jrMayorUno))
                                .addGap(33, 33, 33))
                            .addComponent(jSeparator7))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jlIcMiu, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jbSalirTres)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jtxUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jtNcTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jrMenorUno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtVarDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jtVarUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jbOkTres)
                    .addComponent(jrMayorUno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtsUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtnTresUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel22)
                    .addComponent(jtnTresDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalirTres)
                    .addComponent(jlIcMiu))
                .addContainerGap())
        );

        jtTablaIntervalos.addTab("tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel102.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel102.setText("Diferencia de proporciones");
        jLabel102.setMaximumSize(new java.awt.Dimension(148, 20));
        jLabel102.setMinimumSize(new java.awt.Dimension(148, 20));

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel33.setText("Muestra 1 ( n1 )");

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel34.setText("Resultados \"exitosos\" en la muestra 1 ( p^ 1 )");

        check3.setBackground(new java.awt.Color(255, 255, 255));
        check3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check3ActionPerformed(evt);
            }
        });

        jTextField28.setEnabled(false);

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel35.setText("%");
        jLabel35.setEnabled(false);

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel36.setText("Muestra 2 ( n2 )");

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel37.setText("Resultados \"exitosos\" en la muestra 2 ( p^ 2 )");

        check4.setBackground(new java.awt.Color(255, 255, 255));
        check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check4ActionPerformed(evt);
            }
        });

        jTextField45.setEnabled(false);

        jLabel103.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel103.setText("Nivel de confianza");

        jLabel104.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel104.setText("%");

        botonCalcular8.setText("Calcular");
        botonCalcular8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCalcular8MouseClicked(evt);
            }
        });

        jLabel38.setText("Usar %");

        jLabel105.setText("Usar %");

        jLabel106.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel106.setText("%");
        jLabel106.setEnabled(false);

        jLabel76.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(0, 0, 204));

        jSeparator6.setForeground(new java.awt.Color(0, 51, 204));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(67, 67, 67)
                                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel36)
                                .addGap(58, 58, 58)
                                .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(check3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel35))
                                    .addComponent(jLabel103))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel104))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel105)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(check4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel106)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botonCalcular8)))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                            .addComponent(jSeparator6)
                            .addComponent(jLabel78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel36)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(check3)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)
                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel105))
                    .addComponent(check4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel106)
                        .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel103)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel104))
                    .addComponent(botonCalcular8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jtTablaIntervalos.addTab("Diferencia de proporciones", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtTablaIntervalos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtTablaIntervalos)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtSigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSigmaActionPerformed

    private void jrnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrnMenorActionPerformed
        // TODO add your handling code here:
        if (jrnMenor.isSelected()) {
            jrnMayor.setSelected(false);
            jtS.setEditable(true);
            jtX.setEditable(true);
            jtNc.setEditable(true);
            jtn.setEditable(true);
            jtSigma.setEditable(false);
        } else {
            jtS.setEditable(false);
            jtX.setEditable(false);
            jtNc.setEditable(false);
            jtn.setEditable(false);
            jtSigma.setEditable(false);
        }
    }//GEN-LAST:event_jrnMenorActionPerformed

    private void jrnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrnMayorActionPerformed
        // TODO add your handling code here:
        if (jrnMayor.isSelected()) {
            jrnMenor.setSelected(false);
            jtS.setEditable(false);
            jtX.setEditable(true);
            jtNc.setEditable(true);
            jtn.setEditable(true);
            jtSigma.setEditable(true);
        } else {
            jtS.setEditable(false);
            jtX.setEditable(false);
            jtNc.setEditable(false);
            jtn.setEditable(false);
            jtSigma.setEditable(false);
        }
    }//GEN-LAST:event_jrnMayorActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        // TODO add your handling code here:
        if (jrnMenor.isSelected()) {
            if (jtS.getText().equals("") || jtX.getText().equals("") || jtNc.getText().equals("") || jtn.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!");
            } else {
                if (Globales.verificarNumoDouble(jtS.getText()) && Globales.verificarNumoDouble(jtX.getText()) && Globales.verificarNumoDouble(jtNc.getText()) && Globales.verificarNumoDouble(jtn.getText())) {
                    try {
                        double x = Double.parseDouble(jtX.getText());
                        double s = Double.parseDouble(jtS.getText());
                        int n = Integer.parseInt(jtn.getText());
                        double nc = Double.parseDouble(jtNc.getText());
                        if (n <= 30) {
                            if (nc < 1) {
                                nc = nc * 100;
                            }
                            if (nc <= 100.0 && nc > 89.0) {
                                jlIcX.setText("Intervalo Confianza (X) = " + control.intervaloTstudent(x, n, s, nc));
                            } else {
                                JOptionPane.showMessageDialog(this, "Digite un nivel de confianza enre el 90% y 100%");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "El tamaño de la muestra debe ser menor o igual a 30");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(panelIntervalos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los datos no son numeros!!");
                }
            }
        }
        if (jrnMayor.isSelected()) {
            if (jtSigma.getText().equals("") || jtX.getText().equals("") || jtNc.getText().equals("") || jtn.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!");
            } else {
                if (Globales.verificarNumoDouble(jtSigma.getText()) && Globales.verificarNumoDouble(jtX.getText()) && Globales.verificarNumoDouble(jtNc.getText()) && Globales.verificarNumoDouble(jtn.getText())) {
                    double x = Double.parseDouble(jtX.getText());
                    double s = Double.parseDouble(jtSigma.getText());
                    int n = Integer.parseInt(jtn.getText());
                    double nc = Double.parseDouble(jtNc.getText());
                    if (n > 30) {
                        if (nc >= 0 && nc <= 100) {
                            if (nc > 0 && nc <= 1) {
                                nc = nc * 100;
                            }
                            try {
                                jlIcX.setText("Intervalo Confianza (X) = " + control.intervaloAlfaMediosZ(x, nc, s, n));
                            } catch (IOException ex) {
                                Logger.getLogger(panelIntervalos.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Los porcentajes deven ser en forma decimal o de 0 a 100");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El tamaño de la Muestra debe ser mayor que 30");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Los datos no son numeros!!");
                }
            }
        }


    }//GEN-LAST:event_jbOkActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbSalirUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirUnoActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirUnoActionPerformed

    private void jbSalirDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirDosActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirDosActionPerformed

    private void jbSalirTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirTresActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirTresActionPerformed

    private void jbOkDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkDosActionPerformed
        // TODO add your handling code here:
        if (jtp.getText().equals("") || jynDos.getText().equals("") || jtNcDos.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hay campos Vacios!!!");
        } else {
            if (Globales.verificarNumoDouble(jtp.getText()) && Globales.verificarNumoDouble(jynDos.getText()) && Globales.verificarNumoDouble(jtNcDos.getText())) {
                double p = Double.parseDouble(jtp.getText());
                int n = Integer.parseInt(jynDos.getText());
                if (n > 0) {
                    if (p >= 0) {
                        double nc = (Math.round(Double.parseDouble(jtNcDos.getText()) * 100d) / 100d);
                        if (nc < 1.0) {
                            nc *= 100;
                        }
                        if (nc >= 0 && nc <= 100) {
                            try {
//                                if ((nc <= 20 && nc > 1) || (nc <= 0.2 && nc > 0)) {
//                                    jlIcP.setText("Intervalo De Confianza(p) = [ " + nc + " ; " + -nc + " ]");
//                                } else {
                                    jlIcP.setText("Intervalo De Confianza(p) = " + control.intervalosPGorro(p, nc, n));
                                //}

                            } catch (IOException ex) {
                                Logger.getLogger(panelIntervalos.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "El nivel de confianza no puede ser negativo  o superior al 100%!!!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Digite numeros positivos !!  ");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se admiten muestras negativas!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Los Datos no son numeros Correctos !!!");
            }
        }
    }//GEN-LAST:event_jbOkDosActionPerformed

    private void jrMenorUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMenorUnoActionPerformed
        // TODO add your handling code here:
        if (jrMenorUno.isSelected()) {
            jrMayorUno.setSelected(false);
            jtxUno.setEditable(true);
            jtxDos.setEditable(true);
            jtNcTres.setEditable(true);
            jtnTresDos.setEditable(true);
            jtnTresUno.setEditable(true);
            jtsUno.setEditable(true);
            jtSdos.setEditable(true);
            jtVarDos.setEditable(false);
            jtVarUno.setEditable(false);
        } else {
            jtxUno.setEditable(false);
            jtxDos.setEditable(false);
            jtNcTres.setEditable(false);
            jtnTresDos.setEditable(false);
            jtsUno.setEditable(false);
            jtVarDos.setEditable(false);
            jtnTresUno.setEditable(false);
            jtsUno.setEditable(false);
            jtSdos.setEditable(false);
        }
    }//GEN-LAST:event_jrMenorUnoActionPerformed

    private void jrMayorUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMayorUnoActionPerformed
        // TODO add your handling code here:
        if (jrMayorUno.isSelected()) {
            jrMenorUno.setSelected(false);
            jtxUno.setEditable(true);
            jtxDos.setEditable(true);
            jtNcTres.setEditable(true);
            jtnTresDos.setEditable(true);
            jtsUno.setEditable(false);
            jtSdos.setEditable(false);
            jtVarUno.setEditable(true);
            jtVarDos.setEditable(true);
            jtnTresUno.setEditable(true);
        } else {
            jtxUno.setEditable(false);
            jtxDos.setEditable(false);
            jtNcTres.setEditable(false);
            jtnTresDos.setEditable(false);
            jtsUno.setEditable(false);
            jtVarDos.setEditable(false);
            jtVarUno.setEditable(false);
            jtnTresUno.setEditable(false);
        }
    }//GEN-LAST:event_jrMayorUnoActionPerformed

    private void jbOkTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkTresActionPerformed
        // TODO add your handling code here:
        if (jrMenorUno.isSelected()) {
            if (jtxUno.getText().equals("") || jtxDos.getText().equals("") || jtNcTres.getText().equals("") || jtnTresUno.getText().equals("") || jtnTresDos.getText().equals("") || jtsUno.getText().equals("") || jtSdos.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!");
            } else {
                if (Globales.verificarNumoDouble(jtxUno.getText()) && Globales.verificarNumoDouble(jtxDos.getText()) && Globales.verificarNumoDouble(jtNcTres.getText()) && Globales.verificarNumoDouble(jtnTresUno.getText()) && Globales.verificarNumoDouble(jtnTresDos.getText()) && Globales.verificarNumoDouble(jtSdos.getText()) && Globales.verificarNumoDouble(jtsUno.getText())) {
                    double xUno = Double.parseDouble(jtxUno.getText());
                    double xDos = Double.parseDouble(jtxDos.getText());
                    double nc = Double.parseDouble(jtNcTres.getText());
                    int nUno = Integer.parseInt(jtnTresUno.getText());
                    int nDos = Integer.parseInt(jtnTresDos.getText());
                    double sUno = Double.parseDouble(jtsUno.getText());
                    double sDos = Double.parseDouble(jtSdos.getText());
                    if (nUno > 0 && nUno <= 30 && nDos > 0 && nDos <= 30) {
                        if (sUno > 0 && sDos > 0) {
                            if (nc <= 100 && nc >= 90 || (nc >= 0.90 && nc < 1)) {
                                if (nc > 0 && nc < 1) {
                                    nc *= 100;
                                }
                                try {
                                    System.out.println("a la verga");
                                    jlIcMiu.setText("Intervalo Confianza (µ1 - µ2) = " + control.diferenciaMediasVarDesconocida(xUno, xDos, nUno, nDos, nc, sUno, sDos));
                                } catch (IOException ex) {
                                    Logger.getLogger(panelIntervalos.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "El nivel de confianza debe estar entre el 90% y el 100%");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "El valor de S^2 no puede ser negativo !!!!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El Tamaño de las muestras debe ser menor o igual a 30 \n & no debe ser negativo !!!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los Datos no son Validos !!!!");
                }
            }
        }
        if (jrMayorUno.isSelected()) {
            if (jtxUno.getText().equals("") || jtxDos.getText().equals("") || jtNcTres.getText().equals("") || jtnTresUno.getText().equals("") || jtnTresDos.getText().equals("") || jtVarUno.getText().equals("") || jtVarDos.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!!!");
            }else{
                if(Globales.verificarNumoDouble(jtxUno.getText()) && Globales.verificarNumoDouble(jtxDos.getText()) && Globales.verificarNumoDouble(jtNcTres.getText()) && Globales.verificarNumoDouble(jtVarUno.getText()) && Globales.verificarNumoDouble(jtVarDos.getText()) && Globales.verificarSiEsNum(jtnTresDos.getText()) && Globales.verificarSiEsNum(jtnTresUno.getText())){
                    double xUno  = Double.parseDouble(jtxUno.getText());
                    double xDos = Double.parseDouble(jtxDos.getText());
                    double varUno = Double.parseDouble(jtVarUno.getText());
                    double varDos = Double.parseDouble(jtVarDos.getText());
                    double nc = Double.parseDouble(jtNcTres.getText());
                    int nUno = Integer.parseInt(jtnTresUno.getText());
                    int nDos = Integer.parseInt(jtnTresDos.getText());
                    if(nUno > 30 && nDos > 30){
                        if(varUno > 0 && varDos > 0){
                            if(nc >= 0 && nc <= 100){
                                if(nc > 0 && nc < 1){
                                    nc *= 100;
                                }
                                try {
                                    jlIcMiu.setText("Intervalo Confianza (µ1 - µ2) = " + control.diferenciaMediasVarConocida(xUno, xDos, varUno, varDos, nUno, nDos, nc));
                                } catch (IOException ex) {
                                    Logger.getLogger(panelIntervalos.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }else{
                                JOptionPane.showMessageDialog(this, "El nivel de confianza debe ser del 0% hasta el 100% !!!!");
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "σ^2 no puede ser negativo");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "El tamaño de las muestras debe ser mayor que 30");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Los Datos no son Correctos !!! ");
                }
                
            }
        }
    }//GEN-LAST:event_jbOkTresActionPerformed

    private void jbOkUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkUnoActionPerformed
        // TODO add your handling code here:
        if (jtNcUno.getText().equals("") || jtVar.getText().equals("") || jtnUno.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hay Campos Vacios");
        } else {
            if (Globales.verificarNumoDouble(jtNcUno.getText()) && Globales.verificarNumoDouble(jtVar.getText()) && Globales.verificarNumoDouble(jtnUno.getText())) {
                double nc = Double.parseDouble(jtNcUno.getText());
                double var = Double.parseDouble(jtVar.getText());
                int n = Integer.parseInt(jtnUno.getText());
                if (n > 0 && n <= 30) {
                    if (var > 0) {
                        if (nc >= 0 && nc <= 100) {
                            if (nc > 0 && nc < 1) {
                                nc = nc * 100;
                            }
                            try {
                                jlIcVar.setText("Intervalo Confianza(σ^2) = " + control.getIntervaloAlfaMediosChiCuadrado(nc, n, var));
                            } catch (IOException ex) {
                                Logger.getLogger(panelIntervalos.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "El nivel de Confianza deber ser pocitivo del 0% al 100%");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "S^2 debe ser positivo !!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El tamaño no de la muestra no debe ser negativa y menor que 30 !!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Los Datos No son Correctos !!");
            }

        }
    }//GEN-LAST:event_jbOkUnoActionPerformed

    private void check3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check3ActionPerformed
        // TODO add your handling code here:
        if (check3.isSelected()) {
            jTextField27.setEnabled(false);
            jTextField28.setEnabled(true);
            jLabel33.setEnabled(true);
            verificacion3 = true;
        } else if (check3.isSelected() == false) {
            jTextField27.setEnabled(true);
            jTextField28.setEnabled(false);
            jLabel33.setEnabled(false);
            verificacion3 = false;
        }
    }//GEN-LAST:event_check3ActionPerformed

    private void check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check4ActionPerformed
        // TODO add your handling code here:
        if (check4.isSelected()) {
            jTextField47.setEnabled(false);
            jTextField45.setEnabled(true);
            jLabel106.setEnabled(true);
            verificacion4 = true;
        } else if (check4.isSelected() == false) {
            jTextField47.setEnabled(true);
            jTextField45.setEnabled(false);
            jLabel106.setEnabled(false);
            verificacion4 = false;
        }
    }//GEN-LAST:event_check4ActionPerformed

    private void botonCalcular8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCalcular8MouseClicked
        // TODO add your handling code here:

        String muestra1 = this.jTextField26.getText();
        String pGorro1 = null;
        String pPorcentaje1 = null;
        boolean espacioOcupado1 = false;
        boolean usaPorcentaje1 = false;

        String muestra2 = this.jTextField29.getText();
        String pGorro2 = null;
        String pPorcentaje2 = null;
        boolean espacioOcupado2 = false;
        boolean usaPorcentaje2 = false;

        String intervaloConfianza = this.jTextField46.getText();

        double alfa;
        double z;
        double intervaloMenor;
        double intervaloMayor;
        NormalDistribution f = new NormalDistribution();

        if (verificacion3) {
            pPorcentaje1 = this.jTextField28.getText();
            if (pPorcentaje1.length() != 0) {
                espacioOcupado1 = true;
                usaPorcentaje1 = true;
            }
        } else {
            pGorro1 = this.jTextField27.getText();
            if (pGorro1.length() != 0) {
                espacioOcupado1 = true;
            }
        }

        if (verificacion4) {
            pPorcentaje2 = this.jTextField45.getText();
            if (pPorcentaje2.length() != 0) {
                espacioOcupado2 = true;
                usaPorcentaje2 = true;
            }
        } else {
            pGorro2 = this.jTextField47.getText();
            if (pGorro2.length() != 0) {
                espacioOcupado2 = true;
            }
        }

        if (muestra1.length() != 0 && espacioOcupado1 && muestra2.length() != 0 && espacioOcupado2 && intervaloConfianza.length() != 0) {

            try {
                double n1 = Double.parseDouble(muestra1);
                double p1;
                if (usaPorcentaje1) {
                    p1 = Double.parseDouble(pPorcentaje1);
                    if (p1 >= 1) {
                        p1 = p1 / 100;
                    }
                } else {
                    p1 = Double.parseDouble(pGorro1);
                    p1 = p1 / n1;
                }

                double n2 = Double.parseDouble(muestra2);
                double p2;
                if (usaPorcentaje2) {
                    p2 = Double.parseDouble(pPorcentaje2);
                    if (p2 >= 1) {
                        p2 = p2 / 100;
                    }
                } else {
                    p2 = Double.parseDouble(pGorro2);
                    p2 = p2 / n2;
                }

                double ic = Double.parseDouble(intervaloConfianza);

                if (n1 < 0 || p1 < 0 || n1 < 0 || p2 < 0 || ic < 0) {
                    JOptionPane.showMessageDialog(this, "No puedes ingresar valores negativos", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else if (ic > 100) {
                    JOptionPane.showMessageDialog(this, "El intervalo de confianza debe ser menor o igual a 100 %", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {

                    if (ic >= 1) {
                        ic = ic / 100;
                    }

                    alfa = 1 - ic;
                    alfa = Math.round(alfa * 100d) / 100d;

                    z = f.inverseCumulativeProbability(alfa / 2);
                    z = Math.abs(z);

                    intervaloMenor = (p1 - p2) - z * Math.sqrt((p1 * (1 - p1)) / (n1) + (p2 * (1 - p2)) / (n2));
                    intervaloMayor = (p1 - p2) + z * Math.sqrt((p1 * (1 - p1)) / (n1) + (p2 * (1 - p2)) / (n2));

                    if (intervaloMenor > 0 && intervaloMayor > 0) {
                        
                        jLabel79.setText("P1 > P2");
                        jLabel78.setText("Con un nivel de confianza del " + String.format("%.0f", ic * 100) + "% se puede afirmar que la proporción");
                        jLabel77.setText("poblacional del primer grupo de datos ( P1 ) es mayor a la proporción");
                        jLabel76.setText("poblacional del segundo grupo de datos ( P2 )");
                        jLabel75.setText("IC(" + String.format("%.0f", ic * 100) + "%) (P1 - P2) = [ " + String.format("%.3f", intervaloMenor) + " ; " + String.format("%.3f", intervaloMayor) + " ]");
                    }

                    if (intervaloMenor < 0 && intervaloMayor < 0) {
                        
                        jLabel79.setText("P1 < P2");
                        jLabel78.setText("Con un nivel de confianza del " + String.format("%.0f", ic * 100) + "% se puede afirmar que la proporción");
                        jLabel77.setText("poblacional del primer grupo de datos ( P1 ) es menor a la proporción");
                        jLabel76.setText("poblacional del segundo grupo de datos ( P2 )");
                        jLabel75.setText("IC(" + String.format("%.0f", ic * 100) + "%) (P1 - P2) = [ " + String.format("%.3f", intervaloMenor) + " ; " + String.format("%.3f", intervaloMayor) + " ]");
                    }

                    if (intervaloMenor < 0 && intervaloMayor > 0) {
                       
                        jLabel79.setText("");
                        jLabel78.setText("Con los muestreos realizados no se puede afirmar o determinar");
                        jLabel77.setText("que existan diferencias significativas entre P1 y P2");
                        jLabel76.setText("");
                        jLabel75.setText("IC(" + String.format("%.0f", ic * 100) + "%) (P1 - P2) = [ " + String.format("%.3f", intervaloMenor) + " ; " + String.format("%.3f", intervaloMayor) + " ]");
                    }
                }

            } catch (NumberFormatException e) {
                //Si ocurre un error durante el casteo el programa muestra un aviso correspondiente para que el usuario lo corrija
                JOptionPane.showMessageDialog(this, "Los tipos de datos no coinciden\nVerifique e intente de nuevo", "Información", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No debes dejar espacios en blanco", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_botonCalcular8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular8;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbOkDos;
    private javax.swing.JButton jbOkTres;
    private javax.swing.JButton jbOkUno;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSalirDos;
    private javax.swing.JButton jbSalirTres;
    private javax.swing.JButton jbSalirUno;
    private javax.swing.JLabel jlIcMiu;
    private javax.swing.JLabel jlIcP;
    private javax.swing.JLabel jlIcVar;
    private javax.swing.JLabel jlIcX;
    private javax.swing.JRadioButton jrMayorUno;
    private javax.swing.JRadioButton jrMenorUno;
    private javax.swing.JRadioButton jrnMayor;
    private javax.swing.JRadioButton jrnMenor;
    private javax.swing.JTextField jtNc;
    private javax.swing.JTextField jtNcDos;
    private javax.swing.JTextField jtNcTres;
    private javax.swing.JTextField jtNcUno;
    private javax.swing.JTextField jtS;
    private javax.swing.JTextField jtSdos;
    private javax.swing.JTextField jtSigma;
    private javax.swing.JTabbedPane jtTablaIntervalos;
    private javax.swing.JTextField jtVar;
    private javax.swing.JTextField jtVarDos;
    private javax.swing.JTextField jtVarUno;
    private javax.swing.JTextField jtX;
    private javax.swing.JTextField jtn;
    private javax.swing.JTextField jtnTresDos;
    private javax.swing.JTextField jtnTresUno;
    private javax.swing.JTextField jtnUno;
    private javax.swing.JTextField jtp;
    private javax.swing.JTextField jtsUno;
    private javax.swing.JTextField jtxDos;
    private javax.swing.JTextField jtxUno;
    private javax.swing.JTextField jynDos;
    // End of variables declaration//GEN-END:variables
    private ControlConsulta control;
}
