/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlConsulta;
import Control.Globales;
import static Vista.VistaPrincipal.escritorio;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SeeD
 */
public class panelZ extends javax.swing.JPanel {

    /**
     * Creates new form carcularz
     */
    public panelZ(ControlConsulta control) {
        initComponents();
        this.jtTablaDistribucion.setTitleAt(0, "Proba. (Z)");
        this.jtTablaDistribucion.setTitleAt(1, "Proba. (P)");
        this.control = control;
        this.control.cargarDatosPz(jtSigma, jtSigmaUno, jtMiu, jtMiuUno, jtn);
    }

    /**
     * 0
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtTablaDistribucion = new javax.swing.JTabbedPane();
        jpProbaZ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrDarValorZ = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtK = new javax.swing.JTextField();
        jtPorcentaje = new javax.swing.JTextField();
        jtMiu = new javax.swing.JTextField();
        jtZuno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCsignoDos = new javax.swing.JComboBox<>();
        jCsignoUno = new javax.swing.JComboBox<>();
        jtZdos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtSigma = new javax.swing.JTextField();
        jrHallarK = new javax.swing.JRadioButton();
        jbSlir = new javax.swing.JButton();
        jbCalcular = new javax.swing.JButton();
        jbCalcularKoZ = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jpProbaP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jrDistriX = new javax.swing.JRadioButton();
        jrProporcionMu = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcDos = new javax.swing.JComboBox<>();
        jcUno = new javax.swing.JComboBox<>();
        jtPuno = new javax.swing.JTextField();
        jtPdos = new javax.swing.JTextField();
        jtPorcenUno = new javax.swing.JTextField();
        jtMiuUno = new javax.swing.JTextField();
        jtSigmaUno = new javax.swing.JTextField();
        jtPgorro = new javax.swing.JTextField();
        jtP = new javax.swing.JTextField();
        jtn = new javax.swing.JTextField();
        jbOkUno = new javax.swing.JButton();
        jbCalcularUno = new javax.swing.JButton();
        jbSalirUno = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtXbarra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();

        jtTablaDistribucion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpProbaZ.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Digite Valores de la Tabla \"Z\" en forma de intervalo");

        jrDarValorZ.setBackground(new java.awt.Color(255, 255, 255));
        jrDarValorZ.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrDarValorZ.setText("De un valor a \"Z\" Para Cualquiera De Las Casillas En Azul");
        jrDarValorZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDarValorZActionPerformed(evt);
            }
        });

        jLabel2.setText("K  ");

        jLabel3.setText("µ");

        jLabel4.setText("% ");

        jtK.setEditable(false);

        jtPorcentaje.setEditable(false);
        jtPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcentajeActionPerformed(evt);
            }
        });

        jtMiu.setEditable(false);

        jtZuno.setBackground(new java.awt.Color(50, 170, 222));
        jtZuno.setSelectionColor(new java.awt.Color(130, 212, 248));

        jLabel5.setText("Z");

        jCsignoDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">" }));

        jCsignoUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">" }));

        jtZdos.setBackground(new java.awt.Color(50, 170, 222));
        jtZdos.setSelectionColor(new java.awt.Color(130, 212, 248));

        jLabel6.setText("σ");

        jtSigma.setEditable(false);

        jrHallarK.setBackground(new java.awt.Color(255, 255, 255));
        jrHallarK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrHallarK.setText("Halle un \"K\"");
        jrHallarK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrHallarKActionPerformed(evt);
            }
        });

        jbSlir.setText("Salir");
        jbSlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSlirActionPerformed(evt);
            }
        });

        jbCalcular.setText("OK");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jbCalcularKoZ.setText("Calcular");
        jbCalcularKoZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularKoZActionPerformed(evt);
            }
        });

        jLabel15.setText("O en cualquiera de las casillas que estan en Azul");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Valores de Z:");

        javax.swing.GroupLayout jpProbaZLayout = new javax.swing.GroupLayout(jpProbaZ);
        jpProbaZ.setLayout(jpProbaZLayout);
        jpProbaZLayout.setHorizontalGroup(
            jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProbaZLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProbaZLayout.createSequentialGroup()
                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProbaZLayout.createSequentialGroup()
                                .addComponent(jrHallarK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jrDarValorZ, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jpProbaZLayout.createSequentialGroup()
                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProbaZLayout.createSequentialGroup()
                                .addComponent(jbCalcularKoZ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSlir))
                                .addContainerGap())
                            .addGroup(jpProbaZLayout.createSequentialGroup()
                                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtSigma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jtMiu)
                                    .addComponent(jtPorcentaje)
                                    .addComponent(jtK))
                                .addGap(53, 53, 53)
                                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProbaZLayout.createSequentialGroup()
                                        .addComponent(jtZuno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCsignoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCsignoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtZdos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69))
                                    .addGroup(jpProbaZLayout.createSequentialGroup()
                                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                                        .addGap(15, 15, 15))))))))
        );
        jpProbaZLayout.setVerticalGroup(
            jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProbaZLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jrDarValorZ, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrHallarK)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProbaZLayout.createSequentialGroup()
                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtMiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProbaZLayout.createSequentialGroup()
                        .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtZdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCsignoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCsignoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtZuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jpProbaZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSlir)
                    .addComponent(jbCalcularKoZ))
                .addGap(22, 22, 22))
        );

        jtTablaDistribucion.addTab("tab1", jpProbaZ);

        jpProbaP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("%");

        jLabel8.setText("µ");

        jLabel9.setText("σ");

        jLabel10.setText("p");

        jrDistriX.setBackground(new java.awt.Color(255, 255, 255));
        jrDistriX.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrDistriX.setText("Distribucion Muestral para (μ)");
        jrDistriX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDistriXActionPerformed(evt);
            }
        });

        jrProporcionMu.setBackground(new java.awt.Color(255, 255, 255));
        jrProporcionMu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrProporcionMu.setText("Proporcion Muestral (p)");
        jrProporcionMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrProporcionMuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("P");

        jLabel12.setText("n");

        jLabel13.setText("Z");

        jcDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">" }));

        jcUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">" }));

        jtPuno.setBackground(new java.awt.Color(50, 170, 222));

        jtPdos.setBackground(new java.awt.Color(50, 170, 222));

        jtPorcenUno.setEditable(false);

        jtMiuUno.setEditable(false);

        jtSigmaUno.setEditable(false);

        jtPgorro.setEditable(false);

        jtP.setEditable(false);

        jtn.setEditable(false);

        jbOkUno.setText("ok");
        jbOkUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkUnoActionPerformed(evt);
            }
        });

        jbCalcularUno.setText("Calcular");
        jbCalcularUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularUnoActionPerformed(evt);
            }
        });

        jbSalirUno.setText("Salir");
        jbSalirUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirUnoActionPerformed(evt);
            }
        });

        jLabel14.setText("X");

        jtXbarra.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText(" Valores de \"Z\" :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Halle valores para \"Z\" segun los criterios de la Proporcion Muestral ò la Distribucion Muestral.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Para cualquiera de las casillas en azul");

        jLabel21.setText("\"Calcular\" para dar un valor a las casillas en azul. \"OK\" para hallar el porcentaje");

        jLabel18.setText("^");

        javax.swing.GroupLayout jpProbaPLayout = new javax.swing.GroupLayout(jpProbaP);
        jpProbaP.setLayout(jpProbaPLayout);
        jpProbaPLayout.setHorizontalGroup(
            jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProbaPLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jpProbaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProbaPLayout.createSequentialGroup()
                        .addComponent(jrDistriX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrProporcionMu)
                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(jpProbaPLayout.createSequentialGroup()
                                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtPgorro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtP)))
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbCalcularUno))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalirUno))
                    .addGroup(jpProbaPLayout.createSequentialGroup()
                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpProbaPLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtMiuUno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpProbaPLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtXbarra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpProbaPLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtSigmaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpProbaPLayout.createSequentialGroup()
                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtPuno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcUno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProbaPLayout.createSequentialGroup()
                                .addComponent(jcDos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPdos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbOkUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtPorcenUno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProbaPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jpProbaPLayout.setVerticalGroup(
            jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProbaPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrProporcionMu)
                    .addComponent(jrDistriX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMiuUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtPgorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSigmaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jbCalcularUno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jtXbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProbaPLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbSalirUno)
                                .addComponent(jbOkUno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtPdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jcUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtPuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpProbaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jtPorcenUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jtTablaDistribucion.addTab("tab2", jpProbaP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtTablaDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtTablaDistribucion)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkUnoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (jtPuno.getText().equals("") && jtPdos.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "No has digitado ningun Valor");
            } else {
                if (jtPuno.getText().equals("")) {
                    if (Globales.verificarNumoDouble(jtPdos.getText())) {
                        double numero = (Double.parseDouble(jtPdos.getText()));
                        this.jtPorcenUno.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), (String) jcDos.getSelectedItem()) * 100).replace(",", "."));
                    } else {
                        JOptionPane.showMessageDialog(this, "No es un numero!");
                    }
                } else {
                    if (jtPdos.getText().equals("")) {
                        if (Globales.verificarDouble(jtPuno.getText())) {
                            double numero = Double.parseDouble(jtPuno.getText());
                            if (((String) jcUno.getSelectedItem()).equals("<")) {
                                this.jtPorcenUno.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), ">") * 100).replace(",", "."));
                            } else {
                                this.jtPorcenUno.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), "<") * 100).replace(",", "."));
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No es un numero correcto");
                        }
                    }
                }
            }
            if (!jtPuno.getText().equals("") && !jtPdos.getText().equals("")) {
                if (Globales.verificarDouble(jtPuno.getText()) && Globales.verificarDouble(jtPdos.getText())) {
                    double numero = Double.parseDouble(jtPuno.getText());
                    double numeroDos = Double.parseDouble(jtPdos.getText());
                    double resultado;
                    resultado = 100 * control.calcularZporIntervalo(numero, numeroDos, (String) jcUno.getSelectedItem(), (String) jcDos.getSelectedItem(), String.format("%.2f", numero).replace(",", "."), String.format("%.2f", numeroDos).replace(",", "."));
                    jtPorcenUno.setText(String.format("%.2f", resultado).replace(",", "."));
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(panelZ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbOkUnoActionPerformed

    private void jbSalirUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirUnoActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSalirUnoActionPerformed

    private void jrDistriXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDistriXActionPerformed
        // TODO add your handling code here:
        if (jrDistriX.isSelected()) {
            jrProporcionMu.setSelected(false);
            jtXbarra.setEditable(true);
            jtMiuUno.setEditable(true);
            jtSigmaUno.setEditable(true);
            jtn.setEditable(true);
            jtPorcentaje.setEditable(false);
            jtP.setEditable(false);
            jtPgorro.setEditable(false);
        } else {
            jtXbarra.setEditable(false);
            jtMiuUno.setEditable(false);
            jtSigmaUno.setEditable(false);
            jtn.setEditable(false);
            jtPorcentaje.setEditable(false);
            jtP.setEditable(false);
            jtPgorro.setEditable(false);
        }
    }//GEN-LAST:event_jrDistriXActionPerformed

    private void jrProporcionMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrProporcionMuActionPerformed
        // TODO add your handling code here:
        if (jrProporcionMu.isSelected()) {
            jrDistriX.setSelected(false);
            jtP.setEditable(true);
            jtPgorro.setEditable(true);
            jtXbarra.setEditable(false);
            jtMiuUno.setEditable(false);
            jtSigmaUno.setEditable(false);
            jtn.setEditable(true);
            jtPorcentaje.setEditable(false);
        } else {
            jtXbarra.setEditable(false);
            jtMiuUno.setEditable(false);
            jtSigmaUno.setEditable(false);
            jtn.setEditable(false);
            jtPorcentaje.setEditable(false);
            jtP.setEditable(false);
            jtPgorro.setEditable(false);
        }
    }//GEN-LAST:event_jrProporcionMuActionPerformed

    private void jbCalcularUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularUnoActionPerformed
        // TODO add your handling code here:
        if (jrProporcionMu.isSelected()) {
            if (jtP.getText().equals("") || jtPgorro.getText().equals("") || jtn.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!!");
            } else {
                if (Globales.verificarNumoDouble(jtP.getText()) && Globales.verificarNumoDouble(jtPgorro.getText()) && Globales.verificarNumoDouble(jtn.getText())) {
                    double n = Double.parseDouble(jtn.getText());
                    if (n >= 100) {

                        double p = Double.parseDouble(jtP.getText());
                        double pG = Double.parseDouble(jtPgorro.getText());
                        if (p >= 0 && p <= 100 && pG >= 0 && pG <= 100) {
                            if (p >= 1 && p <= 100) {
                                p = p / 100;
                            }
                            if (pG >= 1 && pG <= 100) {
                                pG = pG / 100;
                            }
                            double resultado = ((pG - p) / Math.sqrt(((p * (1 - p)) / n)));
                            if (jtPuno.getText().equals("")) {
                                jtPuno.setText(String.format("%.2f", resultado).replace(",", "."));
                            } else {
                                if (jtPdos.getText().equals("")) {
                                    jtPdos.setText(String.format("%.2f", resultado).replace(",", "."));
                                } else {
                                    JOptionPane.showMessageDialog(this, "Los Campos Azules(z) Estan Llenos  !!!!! ");
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Digite Valores de porcentajes no  mayores al 100 % & que no sean Negativos");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El tamaño de la muestra deber mayor o igual a 100");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los Datos No son Validos");
                }
            }
        }
        if (jrDistriX.isSelected()) {
            if (jtXbarra.getText().equals("") || jtMiuUno.getText().equals("") || jtSigmaUno.getText().equals("") || jtn.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!!");
            } else {
                if (Globales.verificarNumoDouble(jtXbarra.getText().replace(",", ".")) && Globales.verificarNumoDouble(jtMiuUno.getText().replace(",", ".")) && Globales.verificarNumoDouble(jtSigmaUno.getText().replace(",", ".")) && Globales.verificarNumoDouble(jtn.getText().replace(",", "."))) {
                    int n = Integer.parseInt(jtn.getText());
                    if (n >= 30) {
                        double xbar = Double.parseDouble(jtXbarra.getText().replace(",", "."));
                        double miu = Double.parseDouble(jtMiuUno.getText().replace(",", "."));
                        double sig = Double.parseDouble(jtSigmaUno.getText().replace(",", "."));
                        if (sig > 0) {
                            double result = ((xbar - miu) / (sig / Math.sqrt(n)));
                            if (jtPuno.getText().equals("")) {
                                jtPuno.setText(String.format("%.2f", result).replace(",", "."));
                            } else {
                                if (jtPdos.getText().equals("")) {
                                    jtPdos.setText(String.format("%.2f", result).replace(",", "."));
                                } else {
                                    JOptionPane.showMessageDialog(this, "Los Campos Azules Estan Llenos!!!!");
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Sigma no puede ser negativa !!!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El tamaño de la muestra debe ser mayor o igual a 30");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los Datos No son Validos");
                }
            }
        }
    }//GEN-LAST:event_jbCalcularUnoActionPerformed

    private void jbCalcularKoZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularKoZActionPerformed
        // TODO add your handling code here:
        if (jrHallarK.isSelected()) {
            if (jtZuno.getText().equals("") || jtMiu.getText().equals("") || jtSigma.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos vacios !!");
            } else {
                if (Globales.verificarNumoDouble(jtMiu.getText()) && Globales.verificarNumoDouble(jtZuno.getText()) && Globales.verificarNumoDouble(jtSigma.getText())) {
                    if (Double.parseDouble(jtSigma.getText()) > 0) {
                        double resultado = ((Double.parseDouble(jtZuno.getText())) * Double.parseDouble(jtSigma.getText())) + Double.parseDouble(jtMiu.getText());
                        jtK.setText(String.format("%.2f", resultado).replace(",", "."));
                    } else {
                        JOptionPane.showMessageDialog(this, " σ No pueden ser Negativa !!!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los datos no son correctos !!");
                }
            }
        }
        if (jrDarValorZ.isSelected()) {
            if (jtK.getText().equals("") && jtMiu.getText().equals("") && jtSigma.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hay Campos Vacios !!");
            } else {
                if (Globales.verificarNumoDouble(jtK.getText()) && Globales.verificarNumoDouble(jtMiu.getText()) && Globales.verificarNumoDouble(jtSigma.getText())) {
                    double miu = Double.parseDouble(jtMiu.getText());
                    double sigm = Double.parseDouble(jtSigma.getText());
                    double ksito = Double.parseDouble(jtK.getText());
                    double result = (ksito - miu) / sigm;
                    if ( sigm > 0) {
                        if (jtZuno.getText().equals("")) {
                            jtZuno.setText(String.format("%.2f", result).replace(",", "."));
                        } else {
                            if (jtZdos.getText().equals("")) {
                                jtZdos.setText(String.format("%.2f", result).replace(",", "."));
                            } else {
                                JOptionPane.showMessageDialog(this, "Los Espacion En Azul estan llenos !!!");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "σ No pueden ser Negativa !!!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Los Datos NO Son Correctos !!!!");
                }
            }
        }
    }//GEN-LAST:event_jbCalcularKoZActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        try {
            // TODO add your handling code here:
            if (jtZuno.getText().equals("") && jtZdos.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "No has digitado ningun Valor");
            } else {
                if (jtZuno.getText().equals("")) {
                    if (Globales.verificarNumoDouble(jtZdos.getText())) {
                        double numero = Double.parseDouble(jtZdos.getText());
                        this.jtPorcentaje.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), (String) jCsignoDos.getSelectedItem()) * 100).replace(",", "."));
                        this.jtPorcentaje.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), (String) jCsignoDos.getSelectedItem()) * 100).replace(",", "."));
                    } else {
                        JOptionPane.showMessageDialog(this, "No es un numero!");
                    }
                } else {
                    if (jtZdos.getText().equals("")) {
                        if (Globales.verificarNumoDouble(jtZuno.getText())) {
                            double numero = Double.parseDouble(jtZuno.getText());
                            if (((String) jCsignoUno.getSelectedItem()).equals("<")) {
                                this.jtPorcentaje.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), ">") * 100).replace(",", "."));
                            } else {
                                this.jtPorcentaje.setText(String.format("%.2f", control.calcularZ(String.format("%.2f", numero).replace(",", "."), "<") * 100).replace(",", "."));
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "No es un numero correcto");
                        }
                    }
                }
            }
            if (!jtZuno.getText().equals("") && !jtZdos.getText().equals("")) {
                if (Globales.verificarNumoDouble(jtZuno.getText()) && Globales.verificarNumoDouble(jtZdos.getText())) {
                    double numero = Double.parseDouble(jtZuno.getText());
                    double numeroDos = Double.parseDouble(jtZdos.getText());
                    double resultado;
                    resultado = 100 * control.calcularZporIntervalo(numero, numeroDos, (String) jCsignoUno.getSelectedItem(), (String) jCsignoDos.getSelectedItem(), String.format("%.2f", numero).replace(",", "."), String.format("%.2f", numeroDos).replace(",", "."));
                    jtPorcentaje.setText(String.format("%.2f", resultado).replace(",", "."));
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(panelZ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jbSlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSlirActionPerformed
        // TODO add your handling code here:
        escritorio.getSelectedFrame().dispose();
    }//GEN-LAST:event_jbSlirActionPerformed

    private void jrHallarKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrHallarKActionPerformed
        // TODO add your handling code here:
        if (jrHallarK.isSelected()) {
            jrDarValorZ.setSelected(false);
            jtPorcentaje.setEditable(false);
            jtMiu.setEditable(true);
            jtK.setEditable(false);
            jtZuno.setEditable(true);
            jtZdos.setEditable(false);
            jtSigma.setEditable(true);
        } else {
            jtPorcentaje.setEditable(false);
            jtMiu.setEditable(false);
            jtSigma.setEditable(false);
            jtZuno.setEditable(true);
            jtZdos.setEditable(true);
        }
    }//GEN-LAST:event_jrHallarKActionPerformed

    private void jtPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPorcentajeActionPerformed

    private void jrDarValorZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDarValorZActionPerformed
        // TODO add your handling code here:
        if (jrDarValorZ.isSelected()) {
            jrHallarK.setSelected(false);
            jtPorcentaje.setEditable(false);
            jtK.setEditable(true);
            jtMiu.setEditable(true);
            jtSigma.setEditable(true);
            jtZuno.setEditable(false);
            jtZdos.setEditable(false);
        } else {
            jtPorcentaje.setEditable(false);
            jtK.setEditable(false);
            jtMiu.setEditable(false);
            jtSigma.setEditable(false);
            jtZuno.setEditable(true);
            jtZdos.setEditable(true);
        }
    }//GEN-LAST:event_jrDarValorZActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCsignoDos;
    private javax.swing.JComboBox<String> jCsignoUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbCalcularKoZ;
    private javax.swing.JButton jbCalcularUno;
    private javax.swing.JButton jbOkUno;
    private javax.swing.JButton jbSalirUno;
    private javax.swing.JButton jbSlir;
    private javax.swing.JComboBox<String> jcDos;
    private javax.swing.JComboBox<String> jcUno;
    private javax.swing.JPanel jpProbaP;
    private javax.swing.JPanel jpProbaZ;
    private javax.swing.JRadioButton jrDarValorZ;
    private javax.swing.JRadioButton jrDistriX;
    private javax.swing.JRadioButton jrHallarK;
    private javax.swing.JRadioButton jrProporcionMu;
    private javax.swing.JTextField jtK;
    private javax.swing.JTextField jtMiu;
    private javax.swing.JTextField jtMiuUno;
    private javax.swing.JTextField jtP;
    private javax.swing.JTextField jtPdos;
    private javax.swing.JTextField jtPgorro;
    private javax.swing.JTextField jtPorcenUno;
    private javax.swing.JTextField jtPorcentaje;
    private javax.swing.JTextField jtPuno;
    private javax.swing.JTextField jtSigma;
    private javax.swing.JTextField jtSigmaUno;
    private javax.swing.JTabbedPane jtTablaDistribucion;
    private javax.swing.JTextField jtXbarra;
    private javax.swing.JTextField jtZdos;
    private javax.swing.JTextField jtZuno;
    private javax.swing.JTextField jtn;
    // End of variables declaration//GEN-END:variables
    private ControlConsulta control;
}
