/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlConsulta;
import Control.Globales;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author SeeD(carlos castillo)
 * @author juan david hernandez ing.sistemas
 *
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.control = new ControlConsulta();
        this.jtTables.setTitleAt(0, "Poblacion(N)");
        this.jtTables.setTitleAt(1, "Muestra(n)");
        this.jtMuestra.getColumnModel().getColumn(0).setPreferredWidth(30);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jbImportar = new javax.swing.JButton();
        jbGenerarDatos = new javax.swing.JButton();
        jpResultados = new javax.swing.JPanel();
        jlMedia = new javax.swing.JLabel();
        jlVarianza = new javax.swing.JLabel();
        jlDesciacion = new javax.swing.JLabel();
        jlN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jlMedian = new javax.swing.JLabel();
        jlVarianzan = new javax.swing.JLabel();
        jlDesviacionn = new javax.swing.JLabel();
        jln = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jbGnerarProbabilidad = new javax.swing.JButton();
        jtNuMuestra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtDatoAgregar = new javax.swing.JTextField();
        jtTables = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMuestra = new javax.swing.JTable();
        jbBorrarTabla = new javax.swing.JButton();
        jbBorrarDato = new javax.swing.JButton();
        jcMuestreos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/txt.png"))); // NOI18N
        jbImportar.setToolTipText("Importar archivo");
        jbImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImportarActionPerformed(evt);
            }
        });

        jbGenerarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generate.png"))); // NOI18N
        jbGenerarDatos.setToolTipText("Generar Datos");
        jbGenerarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarDatosActionPerformed(evt);
            }
        });

        jpResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados De La Poblacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jpResultados.setMaximumSize(new java.awt.Dimension(450, 308));

        jlMedia.setText("Media  (N)   :  ");

        jlVarianza.setText("Varianza(N) : ");

        jlDesciacion.setText("Desviacion(N): ");

        jlN.setText("N                      : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resultados Del Muestreo");

        jlMedian.setText("Media (n)     : ");

        jlVarianzan.setText("Varianza(n) : ");

        jlDesviacionn.setText("Desviacion(n) : ");

        jln.setText("n                     : ");

        javax.swing.GroupLayout jpResultadosLayout = new javax.swing.GroupLayout(jpResultados);
        jpResultados.setLayout(jpResultadosLayout);
        jpResultadosLayout.setHorizontalGroup(
            jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addGroup(jpResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpResultadosLayout.createSequentialGroup()
                        .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jlVarianza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlDesciacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlN, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addGroup(jpResultadosLayout.createSequentialGroup()
                        .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlVarianzan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlMedian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlDesviacionn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jln, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jpResultadosLayout.setVerticalGroup(
            jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMedia)
                    .addComponent(jlDesciacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlVarianza)
                    .addComponent(jlN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMedian)
                    .addComponent(jlDesviacionn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlVarianzan)
                    .addComponent(jln))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jbGnerarProbabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campana.png"))); // NOI18N
        jbGnerarProbabilidad.setToolTipText("Probabilidades");
        jbGnerarProbabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGnerarProbabilidadActionPerformed(evt);
            }
        });

        jLabel1.setText("Nº muestra");

        jLabel6.setText("Agregar Dato");

        jtDatoAgregar.setText("0");
        jtDatoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDatoAgregarActionPerformed(evt);
            }
        });

        jtTables.setPreferredSize(new java.awt.Dimension(250, 430));

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Dato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDatos.setColumnSelectionAllowed(true);
        jtDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtDatos);
        jtDatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtDatos.getColumnModel().getColumnCount() > 0) {
            jtDatos.getColumnModel().getColumn(0).setMinWidth(35);
            jtDatos.getColumnModel().getColumn(0).setPreferredWidth(35);
            jtDatos.getColumnModel().getColumn(0).setMaxWidth(35);
            jtDatos.getColumnModel().getColumn(1).setResizable(false);
        }

        jtTables.addTab("tab1", jScrollPane3);

        jtMuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Elemento", "Dato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtMuestra);
        if (jtMuestra.getColumnModel().getColumnCount() > 0) {
            jtMuestra.getColumnModel().getColumn(0).setMinWidth(30);
            jtMuestra.getColumnModel().getColumn(0).setMaxWidth(30);
            jtMuestra.getColumnModel().getColumn(1).setResizable(false);
            jtMuestra.getColumnModel().getColumn(2).setResizable(false);
        }

        jtTables.addTab("tab2", jScrollPane1);

        jbBorrarTabla.setText("Borrar Tabla");
        jbBorrarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarTablaActionPerformed(evt);
            }
        });

        jbBorrarDato.setText("Borrar Dato");
        jbBorrarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarDatoActionPerformed(evt);
            }
        });

        jcMuestreos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Sitematico", "Estratificado", "Conglomerados", "Conv/Cons/Disc", "Por Cuotas" }));
        jcMuestreos.setToolTipText("Generar Muestreo");
        jcMuestreos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMuestreosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corchetes.png"))); // NOI18N
        jButton1.setToolTipText("Intervalos de Confianza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PH.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGenerarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGnerarProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcMuestreos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbBorrarDato)
                                .addGap(36, 36, 36)
                                .addComponent(jbBorrarTabla)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jtDatoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNuMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcMuestreos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGenerarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGnerarProbabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtDatoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNuMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtTables, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBorrarDato)
                    .addComponent(jbBorrarTabla))
                .addGap(7, 7, 7))
        );

        jtTables.getAccessibleContext().setAccessibleName("kj\n");

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcMuestreosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMuestreosActionPerformed
        // TODO add your handling code here:
        if (this.jtNuMuestra.equals("")) {
            JOptionPane.showMessageDialog(this, "Digite Un Valor Para La Muestra a Generar");
        } else {
            if (Globales.verificarSiEsNum(this.jtNuMuestra.getText())) {
                control.getConsulta().setn(Integer.parseInt(this.jtNuMuestra.getText()));
                if (control.getConsulta().getn() < 1 || control.getConsulta().getn() > control.getConsulta().getN()) {
                    JOptionPane.showMessageDialog(this, "El Tamaño de La Muestra No Puede ser Mayor a La de la Poblacion o < 0");
                    control.getConsulta().setn(0);
                } else {
                    if (this.jtDatos.getRowCount() > 0) {
                        if (this.jcMuestreos.getSelectedIndex() == 0) {
                            control.aleatorioSimple();
                            this.jtMuestra.setModel(Globales.cargarDatosJtable(control.getConsulta().getnDatos(), control.getConsulta().getElementos()));
                        }
                        if (this.jcMuestreos.getSelectedIndex() == 1) {
                            control.aleatorioSistematico();
                            this.jtMuestra.setModel(Globales.cargarDatosJtable(control.getConsulta().getnDatos(), control.getConsulta().getElementos()));
                        }
                        if (this.jcMuestreos.getSelectedIndex() == 2) {
                            Globales.cerrarVentanas(escritorio);
                            escritorio.add(Globales.returnInternal(new aleatorioEstratificado(this.control), "Muestro por Estratos"));
                            xCenter = escritorio.getWidth() / 2 - 200;
                            yCenter = escritorio.getHeight() / 2 - 200;
                            escritorio.getAllFrames()[0].setLocation(xCenter, yCenter);
                            escritorio.getAllFrames()[0].toFront();
                        }
                        if (this.jcMuestreos.getSelectedIndex() == 3) {
                            Globales.cerrarVentanas(escritorio);
                            escritorio.add(Globales.returnInternal(new aleatorioConglomerados(control), "Muestreo Por Conglomerados"));
                            xCenter = escritorio.getWidth() / 2 - 200;
                            yCenter = escritorio.getHeight() / 2 - 150;
                            escritorio.getAllFrames()[0].setLocation(xCenter, yCenter);
                            escritorio.getAllFrames()[0].toFront();
                        }
                        if (this.jcMuestreos.getSelectedIndex() == 4) {
                            Globales.cerrarVentanas(escritorio);
                            escritorio.add(Globales.returnInternal(new convConsDisc(control), "Muestreo : Convivencia, Consecitivo & Discrecional"));
                            xCenter = escritorio.getWidth() / 2 - 200;
                            yCenter = escritorio.getHeight() / 2 - 200;
                            escritorio.getAllFrames()[0].setLocation(xCenter, yCenter);
                            escritorio.getAllFrames()[0].toFront();
                        }
                        if (this.jcMuestreos.getSelectedIndex() == 5) {
                            Globales.cerrarVentanas(escritorio);
                            escritorio.add(Globales.returnInternal(new muestreoCuotas(control), "Muestreo Por Cutas"));
                            xCenter = escritorio.getWidth() / 2 - 250;
                            yCenter = escritorio.getHeight() / 2 - 200;
                            escritorio.getAllFrames()[0].setLocation(xCenter, yCenter);
                            escritorio.getAllFrames()[0].toFront();
                        }
                        this.jtTables.setSelectedIndex(1);
                        this.jtMuestra.getColumnModel().getColumn(0).setPreferredWidth(30);
                    } else {
                        JOptionPane.showMessageDialog(this, "No Hay Datos En La Poblacion ");
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "El Tamaño de la Muestra No es Un Numero Valido");
            }

        }
    }//GEN-LAST:event_jcMuestreosActionPerformed

    private void jbBorrarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarDatoActionPerformed
        // TODO add your handling code here:
        if (this.jtDatos.getRowCount() > 0) {
            if (jtDatos.getSelectedRow() >= 0) {
                control.removerDatoN(this.jtDatos.getSelectedRow());
                Globales.removeInList(jtDatos, this.jtDatos.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(this, "selecione el dato a eliminar ");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Tabla de datos vacia!!!");
        }
    }//GEN-LAST:event_jbBorrarDatoActionPerformed

    private void jbBorrarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarTablaActionPerformed
        // TODO add your handling code here:
        if (jtTables.getSelectedIndex() == 0) {
            control.getConsulta().getDatos().clear();
            Globales.removeList(this.jtDatos);
        }
        if (jtTables.getSelectedIndex() == 1) {
            control.getConsulta().getnDatos().clear();
            Globales.removeList(this.jtMuestra);
        }
    }//GEN-LAST:event_jbBorrarTablaActionPerformed

    private void jtDatoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDatoAgregarActionPerformed
        // TODO add your handling code here:
        if (this.jtDatoAgregar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El campo esta vacio!!");
        } else {
            if (Globales.verificarSiEsNum(jtDatoAgregar.getText())) {
                Globales.agregarDatoTabla(jtDatos, Double.parseDouble(jtDatoAgregar.getText()));
                control.getConsulta().getDatos().add(Double.parseDouble(jtDatoAgregar.getText()));
                control.getConsulta().setN(control.getConsulta().getN() + 1);
                this.jtDatoAgregar.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Digite Un Dato Vlido!!");
            }
        }
    }//GEN-LAST:event_jtDatoAgregarActionPerformed

    private void jbGnerarProbabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGnerarProbabilidadActionPerformed
        // TODO add your handling code here:
//        Globales.cerrarVentanas(escritorio);
//        escritorio.add(Globales.returnInternal(new panelZ(this.control), "calcular valores z"));
//        escritorio.getAllFrames()[0].toFront();
//        xCenter = escritorio.getWidth() / 2 - 150;
//        yCenter = escritorio.getHeight() / 2 - 150;
//        escritorio.getAllFrames()[0].setLocation(xCenter, yCenter);
            new Distribuciones().setVisible(true);
    }//GEN-LAST:event_jbGnerarProbabilidadActionPerformed

    private void jbGenerarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarDatosActionPerformed
        // TODO add your handling code here:
        if (this.jtTables.getSelectedIndex() == 0) {
            if (this.jtDatos.getRowCount() > 0) {
                control.calcularDatosN();
                //------------------------------------------------------------------------------------
                this.jlMedia.setText("Media   (N)  : " + String.format("%.2f", control.getConsulta().getMedia()));
                this.jlN.setText("N                  : " + Integer.toString(control.getConsulta().getN()));
                this.jlVarianza.setText("Varianza(N): " + String.format("%.2f", control.getConsulta().getVarianza()));
                this.jlDesciacion.setText("Desviacion(N): " + String.format("%.2f", control.getConsulta().getDesviacion()));
            } else {
                JOptionPane.showMessageDialog(this, "Tabla Vacia");
            }
        }

        if (this.jtTables.getSelectedIndex() == 1) {
            if (this.jtMuestra.getRowCount() > 0) {
                control.calcularDatosn();
                //-------------------------------------------------------------------------------
                this.jlMedian.setText("Media   (n)  : " + String.format("%.2f", control.getConsulta().getnMedia()));
                this.jln.setText("n                   : " + Integer.toString(control.getConsulta().getn()));
                this.jlVarianzan.setText("Varianza(n): " + String.format("%.2f", control.getConsulta().getnVarianza()));
                this.jlDesviacionn.setText("Desviacion(n): " + String.format("%.2f", control.getConsulta().getnDesviacion()));
            } else {
                JOptionPane.showMessageDialog(this, "Genere Un Tipo De Muestra Primero");
            }
        }
    }//GEN-LAST:event_jbGenerarDatosActionPerformed

    private void jbImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImportarActionPerformed
        try {
            // TODO add your handling code here:
            if (control.cargarDatos(Globales.iniciarChooser(fChooser)) != false) {
                this.jtDatos.setModel(Globales.cargarDatosJtable(control.getConsulta().getDatos()));
            } else {
                JOptionPane.showMessageDialog(this, "No se Cargaron Los Datos o Algunos datos Del archivo no Son validos");
            }
        } catch (IOException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbImportarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Globales.cerrarVentanas(escritorio);
        escritorio.add(Globales.returnInternal(new panelIntervalos(this.control), "Intervalos Confianza"));
        xCenter = escritorio.getWidth() / 2 - 150;
        yCenter = escritorio.getHeight() / 2 - 150;
        escritorio.getAllFrames()[0].setLocation(xCenter, yCenter);
        escritorio.getAllFrames()[0].toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PruebaDeHipotesis hipotesis = new PruebaDeHipotesis();
        hipotesis.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBorrarDato;
    private javax.swing.JButton jbBorrarTabla;
    private javax.swing.JButton jbGenerarDatos;
    private javax.swing.JButton jbGnerarProbabilidad;
    private javax.swing.JButton jbImportar;
    private javax.swing.JComboBox<String> jcMuestreos;
    private javax.swing.JLabel jlDesciacion;
    private javax.swing.JLabel jlDesviacionn;
    private javax.swing.JLabel jlMedia;
    private javax.swing.JLabel jlMedian;
    private javax.swing.JLabel jlN;
    private javax.swing.JLabel jlVarianza;
    private javax.swing.JLabel jlVarianzan;
    private javax.swing.JLabel jln;
    private javax.swing.JPanel jpResultados;
    private javax.swing.JTextField jtDatoAgregar;
    public static javax.swing.JTable jtDatos;
    public static javax.swing.JTable jtMuestra;
    private javax.swing.JTextField jtNuMuestra;
    public static javax.swing.JTabbedPane jtTables;
    // End of variables declaration//GEN-END:variables
    private static JFileChooser fChooser;
    public ControlConsulta control;
    private int xCenter;
    private int yCenter;
}
